const locationList = [
    "northern andor",
    "southern andor",
    "lafen",
    "cairhien",
    "tar valon",
    "chilera",
    "krethiz",
    "tear",
    "illian",
    "terrabon",
    "trencouche",
    "borderlands",
    "picheap"
]
const defaultSpread = [
    { name: "northern andor", weight: 2 },
    { name: "southern andor", weight: 1 },
    { name: "lafen", weight: 1 },
    { name: "cairhien", weight: 1 },
    { name: "tar valon", weight: 1 },
    { name: "chilera", weight: 1 },
    { name: "krethiz", weight: 1 },
    { name: "tear", weight: 1 },
    { name: "illian", weight: 1 },
    { name: "terrabon", weight: 1 },
    { name: "trencouche", weight: 1 },
    { name: "borderlands", weight: 1 },
    { name: "picheap", weight: 1 }
]
const citySpecificRaceWeight = {
    "baerlon": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 50 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 80 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ]
}
const locationRace = {
    "southern andor": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "northern andor": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "lafen": [
        { name: "human", weight: 100 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "cairhien": [
        { name: "human", weight: 50 },
        { name: "elf", weight: 5 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 200 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "tar valon": [
        { name: "human", weight: 100 },
        { name: "elf", weight: 50 },
        { name: "halfElf", weight: 60 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 40 },
        { name: "halfOrc", weight: 5 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 30 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 5 },
        { name: "genasi", weight: 10 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 50 },
        { name: "goblin", weight: 0 },
        { name: "kenku", weight: 1 }
    ],
    "chilera": [
        { name: "human", weight: 60 },
        { name: "elf", weight: 5 },
        { name: "halfElf", weight: 50 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 40 },
        { name: "tabaxi", weight: 30 },
        { name: "tiefling", weight: 40 },
        { name: "dragonborn", weight: 20 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 10 },
        { name: "goliath", weight: 10 },
        { name: "firbolg", weight: 10 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "krethiz": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 10 },
        { name: "halfElf", weight: 20 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 5 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 20 },
        { name: "tiefling", weight: 10 },
        { name: "dragonborn", weight: 5 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "tear": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 5 },
        { name: "halfElf", weight: 40 },
        { name: "halfing", weight: 20 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "illian": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 5 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 30 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "terrabon": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 15 },
        { name: "halfElf", weight: 40 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "trencouche": [
        { name: "human", weight: 20 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 300 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "borderlands": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "picheap": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 40 },
        { name: "halfElf", weight: 60 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 10 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ],
    "shinar": [
        { name: "human", weight: 150 },
        { name: "elf", weight: 20 },
        { name: "halfElf", weight: 30 },
        { name: "halfing", weight: 30 },
        { name: "dwarf", weight: 30 },
        { name: "gnome", weight: 10 },
        { name: "halfOrc", weight: 10 },
        { name: "tabaxi", weight: 10 },
        { name: "tiefling", weight: 20 },
        { name: "dragonborn", weight: 10 },
        { name: "orc", weight: 1 },
        { name: "tortle", weight: 3 },
        { name: "genasi", weight: 3 },
        { name: "goliath", weight: 3 },
        { name: "firbolg", weight: 3 },
        { name: "goblin", weight: 1 },
        { name: "kenku", weight: 1 }
    ]
}

const weightedJobList = [{ name: "Beggers", weight: 857 },
{ name: "Housewives/Househusbands", weight: 600 },
{ name: "Laborers", weight: 600 },
{ name: "Elderly/Infirm", weight: 500 },
{ name: "Servers (inns, taverns, restaurants)", weight: 171 },
{ name: "Guards (private)", weight: 120 },
{ name: "Clergy Members", weight: 120 },
{ name: "Peddlers", weight: 100 },
{ name: "Porters", weight: 100 },
{ name: "Apprentices", weight: 85 },
{ name: "Domestic Servants", weight: 66 },
{ name: "Guards (city/governmental)", weight: 60 },
{ name: "Journeymen", weight: 60 },
{ name: "Mercenaries", weight: 60 },
{ name: "Sailors", weight: 60 },
{ name: "Students", weight: 60 },
{ name: "Thieves", weight: 60 },
{ name: "Cobblers", weight: 50 },
{ name: "Furniture Makers", weight: 50 },
{ name: "Clothiers, Used", weight: 48 },
{ name: "Grocers", weight: 48 },
{ name: "Warehousers", weight: 48 },
{ name: "Officials", weight: 40 },
{ name: "Dairy Sellers", weight: 37 },
{ name: "Furriers", weight: 37 },
{ name: "Launderers", weight: 37 },
{ name: "Prostitutes", weight: 37 },
{ name: "Bricklayers", weight: 34 },
{ name: "Livestock Merchants", weight: 30 },
{ name: "Slaves", weight: 30 },
{ name: "Tailors", weight: 30 },
{ name: "Weavers", weight: 30 },
{ name: "Pages", weight: 26 },
{ name: "Barbers", weight: 24 },
{ name: "Basket Makers", weight: 24 },
{ name: "Carpenters", weight: 24 },
{ name: "Drapers", weight: 24 },
{ name: "Florists", weight: 24 },
{ name: "Guides/Touts", weight: 24 },
{ name: "Paper/Parchment Makers", weight: 24 },
{ name: "Potters", weight: 24 },
{ name: "Tavern Keepers", weight: 24 },
{ name: "Wheelwrights", weight: 21 },
{ name: "Jewelers", weight: 21 },
{ name: "Blacksmiths", weight: 20 },
{ name: "Caravanner", weight: 17 },
{ name: "Masons", weight: 17 },
{ name: "Bakers", weight: 24 },
{ name: "Soapmakers", weight: 15 },
{ name: "Cooks", weight: 13 },
{ name: "Chandlers", weight: 12 },
{ name: "Rat Catchers", weight: 12 },
{ name: "Traveler", weight: 12 },
{ name: "Watercarriers", weight: 12 },
{ name: "Coopers", weight: 11 },
{ name: "Mercers", weight: 11 },
{ name: "Pastry Makers", weight: 10 },
{ name: "Engravers", weight: 10 },
{ name: "Pawnbroker", weight: 10 },
{ name: "Grooms", weight: 10 },
{ name: "Midwives", weight: 10 },
{ name: "Haberdashers", weight: 9 },
{ name: "Wine Merchants", weight: 9 },
{ name: "Spice Merchants", weight: 8 },
{ name: "Silversmiths", weight: 8 },
{ name: "Tinkers", weight: 8 },
{ name: "Butchers", weight: 7 },
{ name: "Doctors, Unlicensed", weight: 7 },
{ name: "Fishmongers", weight: 7 },
{ name: "Saddlers and Spurriers", weight: 7 },
{ name: "Purse Makers", weight: 7 },
{ name: "Blacksmiths", weight: 6 },
{ name: "Goldsmiths", weight: 6 },
{ name: "Toymakers", weight: 6 },
{ name: "Wool Merchants", weight: 6 },
{ name: "Artists", weight: 6 },
{ name: "Beer Merchants", weight: 6 },
{ name: "Fishers", weight: 6 },
{ name: "Herbalists", weight: 6 },
{ name: "Leatherworkers", weight: 6 },
{ name: "Nannies", weight: 6 },
{ name: "Plasterers", weight: 6 },
{ name: "Tanners", weight: 6 },
{ name: "Rope Makers", weight: 5 },
{ name: "Buckle Makers", weight: 5 },
{ name: "Cutlers", weight: 5 },
{ name: "Fullers", weight: 5 },
{ name: "Glaziers", weight: 5 },
{ name: "Harness Makers", weight: 5 },
{ name: "Painters", weight: 5 },
{ name: "Roofers", weight: 5 },
{ name: "Woodcarvers", weight: 4 },
{ name: "Woodsellers", weight: 4 },
{ name: "Innkeepers", weight: 4 },
{ name: "Doctors, Licensed", weight: 4 },
{ name: "Mendicants", weight: 4 },
{ name: "Bathers", weight: 4 },
{ name: "Brothel Keepers", weight: 4 },
{ name: "Copyists", weight: 4 },
{ name: "Glass Makers", weight: 4 },
{ name: "Hay Merchants", weight: 4 },
{ name: "Instrument Makers", weight: 4 },
{ name: "Locksmiths", weight: 4 },
{ name: "Millers", weight: 3 },
{ name: "Rug Makers", weight: 3 },
{ name: "Sculptors", weight: 2 },
{ name: "Storytellers", weight: 2 },
{ name: "Acrobats, Tumblers", weight: 2 },
{ name: "Jesters", weight: 2 },
{ name: "Jongleurs", weight: 2 },
{ name: "Minstrels", weight: 2 },
{ name: "Teachers", weight: 2 },
{ name: "Bleachers", weight: 2 },
{ name: "Shipmakers", weight: 2 },
{ name: "Bookbinders", weight: 2 },
{ name: "Moneychangers", weight: 2 },
{ name: "Bowyer/Fletchers", weight: 2 },
{ name: "Brewers", weight: 2 },
{ name: "Glove Makers", weight: 2 },
{ name: "Vintner", weight: 2 },
{ name: "Booksellers", weight: 2 },
{ name: "Gardeners", weight: 2 },
{ name: "Girdlers", weight: 1 },
{ name: "Religious souvenir sellers", weight: 1 },
{ name: "Sage/scholar", weight: 1 },
{ name: "Skinners", weight: 1 },
{ name: "Wetnurses", weight: 1 },
{ name: "Armorers", weight: 1 },
{ name: "Weaponsmiths", weight: 1 },
{ name: "Advocates (lawyers)", weight: 1 },
{ name: "Distillers", weight: 1 },
{ name: "Historians", weight: 1 },
{ name: "Illuminators", weight: 1 },
{ name: "Judges", weight: 1 },
{ name: "Librarians", weight: 1 },
{ name: "Perfumers", weight: 1 },
{ name: "Tilers", weight: 1 },
{ name: "Dentists", weight: 1 },
{ name: "Engineers", weight: 1 },
{ name: "Naval Outfitters", weight: 1 },
{ name: "Potionmakers", weight: 1 },
{ name: "Satirists", weight: 1 },
{ name: "Undertakers", weight: 1 },
{ name: "Writers", weight: 5 },
{ name: "Professors", weight: 4 },
{ name: "Restaurantiers", weight: 4 },
{ name: "Architects", weight: 4 },
{ name: "Astrologers", weight: 3 },
{ name: "Clock Makers", weight: 3 },
{ name: "Grain", weight: 3 },
{ name: "Merchants", weight: 3 },
{ name: "Navigators/Pathfinder", weight: 3 },
{ name: "Tax Collectors", weight: 3 },
{ name: "Taxidermists", weight: 3 },
{ name: "Tobacco Merchants", weight: 3 },
{ name: "Vestment Makers", weight: 3 },
{ name: "Alchemists", weight: 3 },
{ name: "Bankers", weight: 3 },
{ name: "Diplomats", weight: 3 },
{ name: "Slavers", weight: 3 },
{ name: "Town Criers", weight: 3 },
{ name: "Bellmakers", weight: 3 },
{ name: "Cartographers", weight: 3 },
{ name: "Dye Makers", weight: 3 },
{ name: "Inventors and Magic Merchants", weight: 3 },]

const originByRace = {
    gnome: "trencouche",
    dwarf: "cairhien",
    halfing: "southern andor",
    elf: "Picheap",
    halfElf: "southern andor",
    tabaxi: "shinar",
    orc: "wastes",
    teifling: "chilera"
}

const cityWeighting = {
    "northern andor": [{ name: "Baerlon", weight: 16000 },
    { name: "Hordon", weight: 15469 },
    { name: "Percasho", weight: 9164 },
    { name: "Stapton", weight: 8530 },
    { name: "Harton", weight: 8510 },
    { name: "Baldon", weight: 8478 },
    { name: "Axerover", weight: 8262 },
    { name: "Canor", weight: 7499 },
    { name: "Emons Field", weight: 7350 },
    { name: "Olborleytes", weight: 7206 },
    { name: "Berford", weight: 7167 },
    { name: "Cartondobu", weight: 7163 },
    { name: "Tutheton", weight: 7134 },
    { name: "Paigwich", weight: 6049 },
    { name: "Peninhe", weight: 2864 },
    { name: "Hittonbu", weight: 2861 },
    { name: "Redkinham", weight: 2843 },
    { name: "Barmouth", weight: 2212 },
    { name: "Hatesbury", weight: 2135 },
    { name: "Maford", weight: 1851 },
    { name: "Redles", weight: 1850 },
    { name: "Yeomyard", weight: 901 },
    { name: "Skipton", weight: 851 },
    { name: "Forough", weight: 850 },
    { name: "Alrigh", weight: 841 },
    { name: "Aresweston", weight: 841 },
    { name: "Witham", weight: 839 },
    { name: "Newleighes", weight: 830 },
    { name: "Kindon", weight: 828 },
    { name: "Clitre", weight: 724 },],
    "southern andor": [{ name: "Camelyn", weight: 130100 },
    { name: "White bridge", weight: 69000 },
    { name: "Alrid", weight: 22468 },
    { name: "Brastonbuse", weight: 22127 },
    { name: "Horford", weight: 22069 },
    { name: "Exning", weight: 19143 },
    { name: "Leigbury", weight: 18786 },
    { name: "Ghealdan", weight: 13044 },
    { name: "Maker", weight: 10465 },
    { name: "Quatnesto", weight: 10128 },
    { name: "Yeokering", weight: 8391 },
    { name: "Skiptonley", weight: 7524 },
    { name: "Atford", weight: 7432 },
    { name: "Sealis", weight: 7193 },
    { name: "Stapton", weight: 7140 },
    { name: "Retester", weight: 7129 },
    { name: "Bambereham", weight: 7128 },
    { name: "Asfielden", weight: 7126 },
    { name: "Stotformin", weight: 7123 },
    { name: "Wathobuton", weight: 7122 },
    { name: "Gacury", weight: 7116 },
    { name: "Barrford bog", weight: 7079 },
    { name: "Wisterpor", weight: 7053 },
    { name: "Wihul", weight: 7030 },
    { name: "Ormouth", weight: 6084 },
    { name: "Hatrinh", weight: 4490 },
    { name: "Granfield", weight: 3473 },
    { name: "Newbig", weight: 2469 },
    { name: "Brurymock", weight: 2457 },
    { name: "Thormouth", weight: 2406 },
    { name: "Midgerid", weight: 2355 },
    { name: "Uxleley", weight: 765 },
    { name: "Mouton", weight: 742 },],
    "lafen": [{ name: "Lugard", weight: 30209 },
    { name: "Berlowbuton", weight: 7420 },
    { name: "Axrid", weight: 6199 },
    { name: "Alinhambe", weight: 5864 },
    { name: "Penton", weight: 5773 },
    { name: "Soutleach", weight: 2522 },
    { name: "Staple", weight: 2489 },],
    "cairhien": [{ name: "Cairhien", weight: 70000 },
    { name: "Borough", weight: 13863 },
    { name: "Aringill", weight: 13000 },
    { name: "Shauheller ", weight: 10000 },
    { name: "Milmore Mountains", weight: 7000 },
    { name: "Whitbuseley", weight: 5436 },
    { name: "Harporden", weight: 4476 },
    { name: "Witford", weight: 1858 },
    { name: "Axridbury", weight: 1714 },
    { name: "Malisho", weight: 1526 },
    { name: "Warton", weight: 934 },
    { name: "Malney", weight: 851 },
    { name: "Portoles", weight: 815 },
    { name: "Quatham", weight: 803 },
    { name: "Tamerbury", weight: 800 },
    { name: "Loutburyme", weight: 798 },
    { name: "Kenceston", weight: 778 },
    { name: "Brumewent", weight: 776 },
    { name: "Thatking", weight: 764 },],
    "tar valon": [{ name: "Tar Valon", weight: 12500 },
    { name: "Charmouth", weight: 7137 },
    { name: "Asinhil", weight: 7124 },
    { name: "Quatfield", weight: 2533 },
    { name: "Buckedonton", weight: 839 },],
    "chilera": [{ name: "Ebou Dar", weight: 95000 },
    { name: "Staptondo", weight: 11225 },
    { name: "Ormouth", weight: 8788 },
    { name: "Bramping", weight: 7385 },
    { name: "Herley", weight: 7091 },
    { name: "Brovermouth", weight: 6771 },
    { name: "Weskesey", weight: 6472 },
    { name: "Altash", weight: 6171 },
    { name: "Alridbury", weight: 5916 },
    { name: "Pordon", weight: 5848 },
    { name: "Credihul", weight: 5831 },
    { name: "Hithestow", weight: 4160 },
    { name: "Balworh", weight: 2773 },
    { name: "Seadedine", weight: 2491 },
    { name: "Tothorough", weight: 2438 },
    { name: "Alborleigh", weight: 2424 },
    { name: "Leregoke", weight: 2383 }],
    "krethiz": [{ name: "Katar", weight: 31079 },
    { name: "Falme", weight: 13000 },
    { name: "Uxrighes", weight: 7055 },
    { name: "Southorough", weight: 7049 },
    { name: "Prestolego", weight: 6391 },
    { name: "Chawbury", weight: 1891 },
    { name: "Porbuse", weight: 1876 },
    { name: "Cleone", weight: 1811 },],
    "tear": [{ name: "Mayen", weight: 14000 },
    { name: "Far Madding", weight: 14000 },
    { name: "Gilodan", weight: 12686 },
    { name: "Whitlereton", weight: 8863 },
    { name: "Pickerleigh", weight: 8285 },
    { name: "Swaveroesey", weight: 7505 },
    { name: "Alenil", weight: 7084 },
    { name: "Keridleters", weight: 2843 },
    { name: "Axrid", weight: 2567 },
    { name: "Carbury", weight: 2566 },
    { name: "Tothone", weight: 2559 },
    { name: "Boverbole", weight: 2548 },
    { name: "Heylesford", weight: 2452 },
    { name: "Barlow", weight: 2440 },
    { name: "Helbury", weight: 1241 },
    { name: "Oskirleigh", weight: 1238 },],
    "illian": [{ name: "Illian", weight: 38000 },
    { name: "Stotreley", weight: 18111 },
    { name: "Tetbuton", weight: 7534 },
    { name: "Charmouth", weight: 7111 },
    { name: "Malboke", weight: 5742 },
    { name: "Botbury", weight: 5404 },
    { name: "Horninle", weight: 2776 },
    { name: "Wesnes", weight: 2430 },
    { name: "Rotham", weight: 2390 },
    { name: "Bridge", weight: 2381 },],
    "terrabon": [{ name: "Elmora", weight: 74010 },
    { name: "Aiel Tafar", weight: 22522 },
    { name: "Hatleho", weight: 8806 },
    { name: "Walinra", weight: 7580 },
    { name: "Tarton", weight: 7189 },
    { name: "Brolidering", weight: 6452 },
    { name: "Seadeford", weight: 6379 },
    { name: "Leigfield", weight: 6367 },
    { name: "Manfield", weight: 4887 },
    { name: "Goden", weight: 3806 },],
    "trencouche": [{ name: "Hatham", weight: 74000 },
    { name: "Soutford", weight: 1698 },
    { name: "Swamer", weight: 808 },
    { name: "Bostedhurt", weight: 794 },
    { name: "Cleomerford", weight: 779 },
    { name: "Treham", weight: 774 },
    { name: "Masinter", weight: 700 },],
    "borderlands": [{ name: "Fal Dara", weight: 14000 },
    { name: "Shienar", weight: 13367 },
    { name: "Burhamber", weight: 7818 },
    { name: "Craftesbu", weight: 7478 },
    { name: "Kandar", weight: 7000 },
    { name: "Saldea", weight: 7000 },
    { name: "Ormouth", weight: 6602 },
    { name: "Wigdon", weight: 6128 },
    { name: "Stanted", weight: 2543 },
    { name: "Kinham", weight: 2396 },
    { name: "Chichin", weight: 1037 },
    { name: "Dhagon", weight: 1008 },
    { name: "Shiford", weight: 861 },
    { name: "Hatfield", weight: 850 },
    { name: "Chilton", weight: 847 },
    { name: "Durton", weight: 844 },
    { name: "Cocker", weight: 844 },
    { name: "Sidgeton", weight: 839 },
    { name: "Winhet", weight: 807 },
    { name: "Arafel", weight: 697 },
    { name: "Maradon", weight: 0 },],
    "picheap": [{ name: "Arid Doman", weight: 13000 },
    { name: "Gabinton", weight: 2195 },
    { name: "Swadewen", weight: 2189 },
    { name: "Malseasal", weight: 2125 },
    { name: "Pertoles", weight: 883 },
    { name: "Wivetowley", weight: 878 },
    { name: "Horny", weight: 867 },
    { name: "Whitleham", weight: 858 },
    { name: "Penwar", weight: 777 },
    { name: "Wathinra", weight: 772 },]
}

module.exports = {
    locationList: () => { return locationList },
    defaultSpread: () => { return defaultSpread },
    citySpecificRaceWeight: () => { return citySpecificRaceWeight },
    locationRace: () => { return locationRace },
    weightedJobList: () => { return weightedJobList },
    originByRace: () => { return originByRace },
    cityWeighting: () => { return cityWeighting }
}